# Generated by Django 5.2.11 on 2026-02-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.URLField()),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.FloatField(default=0)),
                ('badge', models.CharField(blank=True, max_length=20, null=True)),
                ('is_banner', models.BooleanField(default=False)),
                ('is_top', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_new_episode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
