# Generated by Django 5.2.11 on 2026-02-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anireply', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='is_top',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='tags',
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='anime',
            name='badge',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='subtitle',
            field=models.CharField(blank=True, default='HD', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
