# Generated by Django 5.2.11 on 2026-02-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anireply', '0003_anime_created_at_alter_anime_badge_alter_anime_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.ImageField(default='HD', upload_to='anime_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
