# Generated by Django 5.2.11 on 2026-02-21 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anireply', '0004_alter_anime_genre_alter_anime_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='is_banner',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='is_new_episode',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='is_popular',
        ),
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.CharField(default='HD', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='anime',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('youtube_link', models.URLField(help_text='YouTube video link')),
                ('image', models.URLField(blank=True, help_text='Thumbnail image link', null=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='anireply.anime')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
