# Generated by Django 5.2.11 on 2026-02-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anireply', '0005_remove_anime_is_banner_remove_anime_is_new_episode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='is_banner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='is_new_episode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anime',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
