# Generated by Django 5.2.11 on 2026-02-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anireply', '0006_anime_is_banner_anime_is_new_episode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='dubbed_episodes',
            field=models.PositiveIntegerField(default=0, help_text='Nechta qismi dublyaj qilingan'),
        ),
        migrations.AddField(
            model_name='anime',
            name='total_episodes',
            field=models.PositiveIntegerField(default=0, help_text='Anime nechta qismdan iborat'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('anime', 'number')},
        ),
    ]
